name = "forglad"
version = "1.0.0"
license = "MIT"
author = "jordan4ibanez"
maintainer = "jordan4ibanez"
copyright = "Copyright 2024, jordan4ibanez"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[dependencies]
forterm = { git = "https://github.com/jordan4ibanez/forterm" }
string_f90 = { git = "https://github.com/jordan4ibanez/string_f90" }
files_f90 = { git = "https://github.com/jordan4ibanez/files_f90" }
constants_f90 = { git = "https://github.com/jordan4ibanez/constants_f90" }
fglm = { git = "https://github.com/jordan4ibanez/fglm" }

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
